name: course-manager
version: 0.1.0.0
author: Joseph Morag
maintainer: jm@josephmorag.com

dependencies:
  - base <5
  - relude >=1 && <2
  - aeson
  - databass
  - lens
  - servant
  - servant-server
  - time
  - type-level-sets

library:
  source-dirs: src

executables:
  server:
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - course-manager

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - course-manager
      - hspec
      - http-client
      - aeson-qq

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NumDecimals
  - OverloadedStrings
  - PartialTypeSignatures
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
